$(function(){
    if($("#storesSlider").length){
        $('#storesSlider').owlCarousel({
            rtl:GLOBAL['IS_RTL'],
            loop:false,
            dots:false,
            nav:true,
            responsive:{
                0:{
                    items:2
                },
                500:{
                    items:3
                },
                768:{
                    items:4
                },
                1000:{
                    items:6
                },
                1600:{
                    items:8
                }
            }
        })
    }
})
